#!/usr/bin/env bash

# Console colors
red='\033[0;91m'
red_bg='\033[101m'
yellow_bg='\033[43;90m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

KNOWN_ROOT="web"

# ---------- Runtime ------------

if [ -d "$PROJECT_ROOT/$KNOWN_ROOT" ]; then
  echo -e "${yellow}Directory exists${NC}: $PROJECT_ROOT/$KNOWN_ROOT"
  echo "Delete this directory and start Known installation?"
  echo "Press Enter to delete it and continue or Ctrl-C to cancel..."
  read -p ""
fi

rm -r "$PROJECT_ROOT/$KNOWN_ROOT" 2>/dev/null

# Reset containers
fin reset -f

# Install known - dev branch
cd "$PROJECT_ROOT"
fin exec git clone https://github.com/idno/known.git "$KNOWN_ROOT" 
cd "$KNOWN_ROOT"

# TODO UPSTREAM roave/security-advisories dev-master conflicts with idno/known <=1.3.1
fin exec composer remove roave/security-advisories

fin exec composer -n install
cd ..
fin exec php $KNOWN_ROOT/warmup/CLI/CLIInstaller.php install config.ini .docksal/manifest.txt


echo "------------------------------------"
echo -e "${green}Installation complete.${NC}"
echo -e "  URL: ${yellow}https://$VIRTUAL_HOST${NC}"
